### PR TITLE
Complete port of LESS CSS3 Mixins for SCSS

### PR DESCRIPTION
**Pull request by ffdead**
SCSS doesn't support the @arguments keyword (as far as I know?) so all mixins take on parameter $arguments instead:

Using these mixins in SCSS looks like this:

@include transition(bottom 1s $easeInOutQuint);

### CODE REVIEW

**Comment by darcyclarke** [comment]
This looks great David! Haven't done much SCSS myself so I'm not sure how you'd handle something like multiple, comma separated, declarations for gradients and shadows? In LESS we're using the ability to escape strings (http://lesscss.org/#-escaping) to pass in comma delimited values while maintaining a single @arguments variable within the mixin. Example:

``` less
.box-shadow(~"0 0 10px rgba(0, 0, 0, 0.5), inset 0 1px 0 #fff"); 
```

Does SCSS have something similar? If not, we may need to look at supporting something like the following: http://stackoverflow.com/questions/7874507/a-linear-gradient-with-variable-number-of-stops-in-less-or-sass Not pretty and not dynamic but a solution none-the-less. Let me know your thoughts/feedback and then we should make a test suite before merging.

**Comment by ffdead** [comment]
Hi Darcy,
It's possible using the #{} escape sequence, and looks something like this:

```
$color1: rgba(0, 0, 0, 0.5);
$color2: #fff;

@include box-shadow( #{0 0 10px $color1, inset 0 1px 0 $color2} ); 
```

Agree that we should have a test suite going forward. I think Matt has been working on an SCSS port already so maybe he wants to use that one instead of mine.

cheers

**Comment by darcyclarke** [comment]
That's hawt (and good to know). I guess the only problem now is that this repo is coined specifically "LESS-CSS3-Mixins". Maybe we should change the name of the repo to "CSS3-Mixins" so we can include ports like this for Stylus/SASS, thoughts? (cc @MatthewWagerfield)

**Comment by wagerfield** [comment]
Hey Guys, 

As David mentioned, I have been working on a SCSS port already. It's still in the works, but it's using some really nice features of SCSS which LESS does not support. 

With regards to arguments, the SCSS documentation does not suggest that this feature is supported. However, SCSS supports named parameters, so I have set up all the mixins so that they are pre-populated with all the properties listed on w3 with their respective default values. To override any particular param, you can just do @include box-shadow($xOffset: 2px, $blur: 2px); This solution is of course, a lot less flexible than LESS for more complex mixins such as gradients.

Finally, in response to the name of the repo, I will of course be changing it to CSS3-Mixins and will let you know when I push  this update : )

Stay tuned...

**Pull request closed without merging**
